name: updown_arrow_scroller_flutter_heyteacher
description: "A new Flutter package that help scrolling web page using keyboard arrow (forked by heyteacher)."
version: 0.1.2
homepage: https://github.com/heyteacher/updown_arrow_scroller_flutter_heyteacher
repository: https://github.com/heyteacher/updown_arrow_scroller_flutter_heyteacher
license: MIT
issue_tracker: https://github.com/heyteacher/updown_arrow_scroller_flutter_heyteacher/issues
documentation: https://github.com/heyteacher/updown_arrow_scroller_flutter_heyteacher

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0
